version: 2
updates:
  # Enable version updates for Bun
  - package-ecosystem: "bun"
    # Look for `package.json` and `bun.lock` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Assign reviewers
    reviewers:
      - "@your-github-username"
    # Add labels
    labels:
      - "dependencies"
      - "javascript"
    # Create a pull request for version updates
    open-pull-requests-limit: 10
    # Group updates by dependency name
    versioning-strategy: increase
    # Ignore major version updates by default
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
