name: Code Quality

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
          queries: security-extended,security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript,/language:typescript"

  check-dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Check for outdated packages
        run: bun outdated || echo "Some packages are outdated"
        continue-on-error: true
        
      - name: Check for vulnerabilities
        run: bun audit
        continue-on-error: true

  check-dead-urls:
    name: Check Dead URLs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dead links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
